arb-dir: lib/l10n
output dir: lib/l10n/generated
untranslated-messages-file: lib/l10n/missing_localizations.json 
template-arb-file: app_uk.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
synthetic-package: false
preferred-supported-locales: "uk"
use-deferred-loading: false